mywebsite/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace mywebsite.Models
{
    public class Contact
    {
        [Required(ErrorMessage ="این فیلد اجباری است")]
        [MinLength(4 , ErrorMessage ="حداقل طول نام کاربری باید 4 کاراکتر باشد!")]
        [MaxLength(10 , ErrorMessage ="حداکثر طول نام کاربری 10 کاراکتر است!")]
        public string username { get; set; }
        [EmailAddress(ErrorMessage ="ایمیل وارد شده معتبر نیست")]
        [Required(ErrorMessage = "این فیلد اجباری است")]
        public string email { get; set; }
        public string category { get; set; }
        [Required(ErrorMessage = "این فیلد اجباری است")]
        [MinLength(5, ErrorMessage = "حداقل طول پیام باید 5 کاراکتر باشد!")]
        [MaxLength(60, ErrorMessage = "حداکثر طول پیام 60 کاراکتر است!")]
        public string message { get; set; }
    }
}

mywebsite/Models/Discount.cs
namespace mywebsite.Models
{
    //is here somethings code...

    public class Discount
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public string off { get; set; }

        public Discount(int id, string name, string image, int price, string off)
        {
            this.id = id;
            Name = name;
            Image = image;
            Price = price;
            this.off = off;
        }
    }
}

mywebsite/Models/ErrorViewModel.cs
using System;

namespace mywebsite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

mywebsite/Models/Product.cs
using Microsoft.Extensions.Diagnostics.HealthChecks;

namespace mywebsite.Models
{
    public class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }

        public Product(int id, string name, string image, int price)
        {
            this.id = id;
            Name = name;
            Image = image;
            Price = price;
        }
    }
}

mywebsite/Models/indexmodel.cs
using System.Collections.Generic;

namespace mywebsite.Models
{
    public class indexmodel
    {
        public List<Product> Products { get; set; }
        public List<Discount> Discounts { get; set; }

    }
}

mywebsite/Models/info.cs
namespace mywebsite.Models
{
    public class info
    {
        public string phone { get; set; }
        public string email { get; set; }
        public string instagram { get; set; }
    }
}

mywebsite/Models/item.cs
namespace mywebsite.Models
{
    public class item
    {
        public int  id { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string price { get; set; }
        public string link { get; set; }


    }
}

mywebsite/Models/portfolio.cs
namespace mywebsite.Models
{
    public class portfolio
    {
        public int MyProperty { get; set; }
    }
}

mywebsite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mywebsite.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace mywebsite.Controllers
{
    public class HomeController : Controller
    {
        private readonly List<item> _items = new List<item>
        {
            new item
            {
                id = 1,title = "تیشرت مردانه سیاه", image="7a9fc279973941176c49f4ef84938cb137209e82_1670691560.jpg", price ="18$",link= "www.digikala.com"
            },
            new item
            {
                id = 1,title = "تیشرت مردانه سیاه", image="7a9fc279973941176c49f4ef84938cb137209e82_1670691560.jpg", price ="18$",link= "www.digikala.com"
            },
            new item
            {
                id = 1,title = "تیشرت مردانه سیاه", image="7a9fc279973941176c49f4ef84938cb137209e82_1670691560.jpg", price ="18$",link= "www.digikala.com"
            },
            new item
            {
                id = 1,title = "تیشرت مردانه سیاه", image="7a9fc279973941176c49f4ef84938cb137209e82_1670691560.jpg", price ="18$",link= "www.digikala.com"
            },
        };


        public IActionResult Index()
        {
            ViewData["headingTitle"] = "فروشگاه پارس آنلاین";
            ViewData["headingText"] = "فروشگاه آنلاین ما به شما اجازه می‌دهد تا از پیشنهادات بسیاری از محصولات با کیفیت در بازار مصرف کنید. ما در حال حاضر محصولات زیادی ارائه می‌دهیم، از جمله لباس، اکسسوارها، کالای دیجیتال، و ... همچنین، ما تلاش برای ارائه بهترین سرویس پس از فروش و بهبود تجربه خرید شما داریم";

            return View(_items);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Kala()
        {
            return View();
        }

        public IActionResult About()
        {
            var reza = new info()
            {
                phone = "0912345678",
                email = "rezaramezannejad8632@gmail.com",
                instagram = "reza.ram32",
            };
            return View(reza);
        }
        [HttpGet]
        public IActionResult Contact()
        {
            var model = new Contact();
            return View(model);
        }


        //[HttpPost]
        //public JsonResult Contact(IFormCollection form)
        //{
        //    return Json(Ok());
        //}

        [HttpPost]
        public JsonResult Contact(Contact form)
        {
            Console.WriteLine(form.ToString());
            return Json(Ok());
        }
    }
}

mywebsite/Controllers/testController.cs
using Microsoft.AspNetCore.Mvc;

namespace mywebsite.Controllers
{
    public class testController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        //public JsonResult index()
        //{
        //    return Json(new {
        //        id = 1,
        //        name = "reza",
        //        job ="programmer"
        //    } 
        //    );
        //}

        //--------------------------------------------------------------------------------

        //public RedirectResult index()
        //{
        //    return Redirect("https://www.digikala.com");
        //}

        //--------------------------------------------------------------------------------
        
        public RedirectToActionResult index()
        {
            return RedirectToAction("MyProduct", "Home");
        }

    }
}

mywebsite/View component/DiscountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mywebsite.Models;
using System.Collections.Generic;

namespace mywebsite.View_component
{
    public class DiscountViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Discounts = new List<Discount>
            {
                new Discount (1 ,"محصول مورد نظر","83af811f2b8fd43529a00c8d4bdd35a86f59346f_1647152703.jpg",119,"20%"),
                new Discount (2 ,"محصول مورد نظر","83af811f2b8fd43529a00c8d4bdd35a86f59346f_1647152703.jpg",119, "15%"),
                new Discount (3 ,"محصول مورد نظر","83af811f2b8fd43529a00c8d4bdd35a86f59346f_1647152703.jpg",119,"45%"),
            };

            return View("_Discount", Discounts);
        }
    }
}

mywebsite/View component/ProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mywebsite.Models;
using System.Collections.Generic;

namespace mywebsite.View_component
{
    public class ProductViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Products = new List<Product>
            {
                new Product (1 ,"محصول مورد نظر","ahura-theme-1.jpg",119),
                new Product (2 ,"محصول مورد نظر","ahura-theme-1.jpg",119),
                new Product (3 ,"محصول مورد نظر","ahura-theme-1.jpg",119),
            };

            return View("_Product" , Products);
        }
    }
}

mywebsite/Views/Home/Contact.cshtml
@model Contact

@{
    ViewData["Title"] = "ارتباط با ما";
}

<h2>فرم ارتباط با ما</h2>
<form class="bcontact" asp-action="Contact" method="post">
    <label for="username">نام کاربری:</label>
    <input type="text" asp-for="username" >
    <span asp-validation-for="username"></span>

    <label for="email">ایمیل:</label>
    <input type="email" asp-for="email" >
    <span asp-validation-for="email"></span>


    <label asp-for="category">دسته‌بندی محصول:</label>
    <select asp-for="category" >
        <option value="clothing">پوشاک</option>
        <option value="digital">دیجیتال</option>
        <option value="food">خوراکی</option>
    </select>

    <label for="message">پیشنهاد یا نظر:</label>
    <textarea asp-for="message" rows="4" ></textarea>
    <span asp-validation-for="message"></span>

    <button type="submit">ارسال</button>
</form>

mywebsite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "صفحه اصلی ";
}


<section id="home">
    <div class="intro-wrapper">
        <h2 class="iiimmm">فروشگاه آنلاین</h2>
        <p>
            @ViewData["headingTitle"]
        </p>
        <button>محصولات</button>
    </div>
</section>

<section id="aboutus">
    <div class="about-wrapper">
        <div class="about-text">
            <h2>درباره ما</h2>
            <p>
                @ViewData["headingText"]
            </p>
        </div>
    </div>
</section>

<Partial name="MyProduct" />

mywebsite/Views/Home/about.cshtml
@model info
@{
    ViewData["Title"] = "about";
}

<section class="aaa">



    <div class="container">

        <div class="about-section">
            <div class="text">
                <h2>درباره ما</h2>
                <p>با افتخار به معرفی سایت خود می‌پردازیم. سایت ما با هدف ... (توضیحات بیشتر در این قسمت)</p>
            </div>
            <img src="~/about.png" alt="تصویر درباره ما">
        </div>

        <div class="contact-box">
            <div class="contact-item">
                <i class="fas fa-phone-alt"></i>
                <p class="inline">mobile</p>
                <td>@Model.phone</td>
            </div>
            <div class="contact-item">
                <i class="far fa-envelope"></i>
                <p class="inline">Email</p>
                <span>@Model.email</span>
            </div>
            <div class="contact-item">
                <i class="fab fa-instagram"></i>
                <p class="inline">instagram ID</p>
                <td>@Model.instagram</td>
            </div>
        </div>



    </div>

</section>

mywebsite/Views/Home/kala.cshtml
@{
    ViewData["Title"] = "kala";
}

@* <partial name="Prodoct" />
 *@
@* @await Html.PartialAsync("Product")
 *@
@await Component.InvokeAsync("Product")


<p class="offer">حراجی ها</p>


@await Component.InvokeAsync("Discount")

mywebsite/Views/Shared/Components/Discount/_Discount.cshtml
@model List<Discount>


<section>
    <div class="containeroff">
        <div class="row">
            @foreach (var Discount in Model)
            {   
            <div class="productoff">
                <img src="~/@Discount.Image" alt="@Discount.id"/>
                <h2>@Discount.Name</h2>
                <p>@Discount.Price قیمت: </p>
                <p>@Discount.off درصد تخفیف:</p>
            </div>
            }
        </div>


    <!-- دستورات مشابه بالا برای محصولات ۲ تا ۶ قرار بگیرد -->
</section>

mywebsite/Views/Shared/Components/Product/_Product.cshtml
@model IEnumerable<mywebsite.Models.Product>
<section>
    <h1>محصولات پر فروش</h1>
    <div class="product-container" style="margin-right: 0px;">
        @foreach (var Products in Model)
        { 
        <div class="product">
            <img class="imagekala" src="~/@Products.Image" alt=@Products.id>
            <h3>@Products.Name</h3>
            <p>@Products.Price "تومان"</p>
            <button class="buybox">خرید</button>
        </div>
        }
    </div>

</section>

mywebsite/Views/Shared/Footer.cshtml
<footer>
    <div class="social-images">
        <a href="https://t.me/your_telegram_handle" target="_blank">
            <img class=" hhhhh" src="359874_telegram logo High quality High quality_xl-1024-v1-0.png" alt="Telegram">
        </a>
        <a href="https://www.instagram.com/your_instagram_handle" target="_blank">
            <img class=" hhhhh" src="311206_instagram logo High quality High quality_xl-1024-v1-0.png" alt="Instagram">
        </a>
    </div>
    <p>&copy; 2023 فروشگاه آنلاین</p>
</footer>

mywebsite/Views/Shared/Header.cshtml
<header>
    <div class="container header-container">
        <div class="header-content">
            <!-- Replace the logo URL with the one matching your brand -->
            <a href="index" class="logo">
                <img class="logoo" src="~/9bf09583668c9ac9d9d076e60e361f074808034ac3ec61.jpg" alt="home"  />
            </a>
            <nav>
                <ul>
                    <li><a href="@Url.Action("Contact" ,"home")">ارتباط با ما</a></li>
                    <li><a href="@Url.Action("about" ,"home")">| درباره ما</a></li>
                    <li><a href="@Url.Action("kala" ,"home")">|  محصولات</a></li>
                    <li><a href="@Url.Action("index" ,"home")">|  خانه</a></li>

                </ul>
            </nav>
            <span class="mobile-menu-icon">&#9776;</span>
        </div>
    </div>
</header>

mywebsite/Views/Shared/MyProduct.cshtml
@model List<item>
<section id="products">
    <h2>محصولات ما</h2>
    <div class="product-grid">
        @foreach (var item in Model)
        {
            <div class="product-card">

                <img class="immgg" src="~/@item.image" alt="@item.id">
                <div class="product-name"> @item.title</div>
                <a href="@item.link/">
                    <div class="product-price"> @item.price</div>
                </a>

            </div>
        }

    </div>
</section>

mywebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>  پارس شاپ | @ViewData["Title"] </title>
    <link href="~/https://fonts.googleapis.com/css2?family=Vazir&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="~/ASP--STYLES/styles11.css" />
</head>
<body>
    <!-- Hero image with centered text -->
    <div class="hero-image">
        <div class="centered-text">
            <h1>فروشگاه آنلاین</h1>
            <div class="choose-and-buy-container">
                <p>انتخاب کنید و خرید کنید!</p>
            </div>
        </div>
    </div>

    <!-- Site header -->

    <Partial  name="Header"/>

    <!-- Home section -->
    <div>
        @RenderBody()
    </div>

    <!-- Site Footer -->

    <Partial name="Footer" />

    <!-- Home section -->


    <script src="~/scripts.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/lib/jquery-3.4.1.min.js"></script>
    <script src="~/lib/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    @* validation jquery scripts (unobtrusive) *@

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>